# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure ("2") do |config|
    config.vm.box = "chrisurwin/RancherOS"
    #config.vm.box_version = "1.5.8"
    config.ssh.username = "rancher"
    config.vm.hostname = "CS-VM-03"
    config.vm.synced_folder "/", "/home/rancher/shared"
#
end    

