# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure ("2") do |config|
    configure.vm.box = "chrisurwin/RancherOS"
    configure.vm.box_version = "1.5.8"
    configure.ssh.username = "rancher"
    configure.vm.hostname = "CS-VM-03"
    configure.vm.synced_folder "/", "/home/rancher/shared"
#
end    

